version: '2'
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod -smallfiles --logpath=/dev/null # --quiet

  epcis:
    build: .
    container_name: "epcis_repository"
    image: tomcat:latest
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    volumes:
      - ./epcis/target/epcis.war:/usr/local/tomcat/webapps/epcis.war
      - /root/.m2:/root/.m2
    environment:
      - "JAVA_OPTS=-Dmongo.host=mongodb"
